title: "HK UPJŠ Košice"
email: hkupjske@gmail.com
timezone: UTC
baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"
logo: 'assets/images/logo-m.png'
favicon: 'assets/images/climbing-48.ico'
author: Sal
paginate: 30
disqus: 'nasa_stranka'
locale: sk_SK
lang: sk_sk
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 


social:
  instagram: https://www.instagram.com/hkupjske/
  facebook: https://www.facebook.com/HKupjsKE/
  

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
