name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        sshfs horolezci@horolezci.upjs.sk: /home/richard_stana/actions-runner/web_backup/horolezci_sshfs/
        cp -r /home/richard_stana/actions-runner/web_backup/horolezci_sshfs/* /home/richard_stana/actions-runner/web_backup/www_bak/
        rm -r /home/richard_stana/actions-runner/web_backup/horolezci_sshfs/*
        cp -r /home/richard_stana/actions-runner/page_horolezci/affiliates-jekyll-theme/affiliates-jekyll-theme/_site/* /home/richard_stana/actions-runner/web_backup/horolezci_sshfs/
        umount /home/richard_stana/actions-runner/web_backup/horolezci_sshfs/
